// source: pando/api/alarm/v0/equipment.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var pando_api_alarm_v0_equipment$model_pb = require('../../../../pando/api/alarm/v0/equipment-model_pb.js');
goog.object.extend(proto, pando_api_alarm_v0_equipment$model_pb);
var pando_api_alarm_v0_signal$model_pb = require('../../../../pando/api/alarm/v0/signal-model_pb.js');
goog.object.extend(proto, pando_api_alarm_v0_signal$model_pb);
var pando_api_extensions_pb = require('../../../../pando/api/extensions_pb.js');
goog.object.extend(proto, pando_api_extensions_pb);
var pando_api_shared_pb = require('../../../../pando/api/shared_pb.js');
goog.object.extend(proto, pando_api_shared_pb);
goog.exportSymbol('proto.equipment_service.EditSignalsRequest', null, global);
goog.exportSymbol('proto.equipment_service.GetEquipmentByExtensionRequest', null, global);
goog.exportSymbol('proto.equipment_service.GetModelListRequest', null, global);
goog.exportSymbol('proto.equipment_service.GetRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.equipment_service.GetRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.equipment_service.GetRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.equipment_service.GetRequest.displayName = 'proto.equipment_service.GetRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.equipment_service.GetModelListRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.equipment_service.GetModelListRequest.repeatedFields_, null);
};
goog.inherits(proto.equipment_service.GetModelListRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.equipment_service.GetModelListRequest.displayName = 'proto.equipment_service.GetModelListRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.equipment_service.EditSignalsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.equipment_service.EditSignalsRequest.repeatedFields_, null);
};
goog.inherits(proto.equipment_service.EditSignalsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.equipment_service.EditSignalsRequest.displayName = 'proto.equipment_service.EditSignalsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.equipment_service.GetEquipmentByExtensionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.equipment_service.GetEquipmentByExtensionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.equipment_service.GetEquipmentByExtensionRequest.displayName = 'proto.equipment_service.GetEquipmentByExtensionRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.equipment_service.GetRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.equipment_service.GetRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.equipment_service.GetRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.equipment_service.GetRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    equipmentGuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    includeInactive: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.equipment_service.GetRequest}
 */
proto.equipment_service.GetRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.equipment_service.GetRequest;
  return proto.equipment_service.GetRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.equipment_service.GetRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.equipment_service.GetRequest}
 */
proto.equipment_service.GetRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEquipmentGuid(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeInactive(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.equipment_service.GetRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.equipment_service.GetRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.equipment_service.GetRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.equipment_service.GetRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEquipmentGuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIncludeInactive();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional string equipment_guid = 1;
 * @return {string}
 */
proto.equipment_service.GetRequest.prototype.getEquipmentGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.equipment_service.GetRequest} returns this
 */
proto.equipment_service.GetRequest.prototype.setEquipmentGuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool include_inactive = 2;
 * @return {boolean}
 */
proto.equipment_service.GetRequest.prototype.getIncludeInactive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.equipment_service.GetRequest} returns this
 */
proto.equipment_service.GetRequest.prototype.setIncludeInactive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.equipment_service.GetModelListRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.equipment_service.GetModelListRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.equipment_service.GetModelListRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.equipment_service.GetModelListRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.equipment_service.GetModelListRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    includeInactive: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    equipmentGuidsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.equipment_service.GetModelListRequest}
 */
proto.equipment_service.GetModelListRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.equipment_service.GetModelListRequest;
  return proto.equipment_service.GetModelListRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.equipment_service.GetModelListRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.equipment_service.GetModelListRequest}
 */
proto.equipment_service.GetModelListRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeInactive(value);
      break;
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addEquipmentGuids(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.equipment_service.GetModelListRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.equipment_service.GetModelListRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.equipment_service.GetModelListRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.equipment_service.GetModelListRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIncludeInactive();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getEquipmentGuidsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * optional bool include_inactive = 2;
 * @return {boolean}
 */
proto.equipment_service.GetModelListRequest.prototype.getIncludeInactive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.equipment_service.GetModelListRequest} returns this
 */
proto.equipment_service.GetModelListRequest.prototype.setIncludeInactive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * repeated string equipment_guids = 1;
 * @return {!Array<string>}
 */
proto.equipment_service.GetModelListRequest.prototype.getEquipmentGuidsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.equipment_service.GetModelListRequest} returns this
 */
proto.equipment_service.GetModelListRequest.prototype.setEquipmentGuidsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.equipment_service.GetModelListRequest} returns this
 */
proto.equipment_service.GetModelListRequest.prototype.addEquipmentGuids = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.equipment_service.GetModelListRequest} returns this
 */
proto.equipment_service.GetModelListRequest.prototype.clearEquipmentGuidsList = function() {
  return this.setEquipmentGuidsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.equipment_service.EditSignalsRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.equipment_service.EditSignalsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.equipment_service.EditSignalsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.equipment_service.EditSignalsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.equipment_service.EditSignalsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    equipmentGuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    includeInactive: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    signalTypeGuidsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.equipment_service.EditSignalsRequest}
 */
proto.equipment_service.EditSignalsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.equipment_service.EditSignalsRequest;
  return proto.equipment_service.EditSignalsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.equipment_service.EditSignalsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.equipment_service.EditSignalsRequest}
 */
proto.equipment_service.EditSignalsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEquipmentGuid(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeInactive(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addSignalTypeGuids(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.equipment_service.EditSignalsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.equipment_service.EditSignalsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.equipment_service.EditSignalsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.equipment_service.EditSignalsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEquipmentGuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIncludeInactive();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getSignalTypeGuidsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional string equipment_guid = 1;
 * @return {string}
 */
proto.equipment_service.EditSignalsRequest.prototype.getEquipmentGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.equipment_service.EditSignalsRequest} returns this
 */
proto.equipment_service.EditSignalsRequest.prototype.setEquipmentGuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool include_inactive = 3;
 * @return {boolean}
 */
proto.equipment_service.EditSignalsRequest.prototype.getIncludeInactive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.equipment_service.EditSignalsRequest} returns this
 */
proto.equipment_service.EditSignalsRequest.prototype.setIncludeInactive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * repeated string signal_type_guids = 2;
 * @return {!Array<string>}
 */
proto.equipment_service.EditSignalsRequest.prototype.getSignalTypeGuidsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.equipment_service.EditSignalsRequest} returns this
 */
proto.equipment_service.EditSignalsRequest.prototype.setSignalTypeGuidsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.equipment_service.EditSignalsRequest} returns this
 */
proto.equipment_service.EditSignalsRequest.prototype.addSignalTypeGuids = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.equipment_service.EditSignalsRequest} returns this
 */
proto.equipment_service.EditSignalsRequest.prototype.clearSignalTypeGuidsList = function() {
  return this.setSignalTypeGuidsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.equipment_service.GetEquipmentByExtensionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.equipment_service.GetEquipmentByExtensionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.equipment_service.GetEquipmentByExtensionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.equipment_service.GetEquipmentByExtensionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    extenstionName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    extenstionValue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    includeInactive: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.equipment_service.GetEquipmentByExtensionRequest}
 */
proto.equipment_service.GetEquipmentByExtensionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.equipment_service.GetEquipmentByExtensionRequest;
  return proto.equipment_service.GetEquipmentByExtensionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.equipment_service.GetEquipmentByExtensionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.equipment_service.GetEquipmentByExtensionRequest}
 */
proto.equipment_service.GetEquipmentByExtensionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtenstionName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtenstionValue(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeInactive(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.equipment_service.GetEquipmentByExtensionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.equipment_service.GetEquipmentByExtensionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.equipment_service.GetEquipmentByExtensionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.equipment_service.GetEquipmentByExtensionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExtenstionName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExtenstionValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIncludeInactive();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional string extenstion_name = 1;
 * @return {string}
 */
proto.equipment_service.GetEquipmentByExtensionRequest.prototype.getExtenstionName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.equipment_service.GetEquipmentByExtensionRequest} returns this
 */
proto.equipment_service.GetEquipmentByExtensionRequest.prototype.setExtenstionName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string extenstion_value = 2;
 * @return {string}
 */
proto.equipment_service.GetEquipmentByExtensionRequest.prototype.getExtenstionValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.equipment_service.GetEquipmentByExtensionRequest} returns this
 */
proto.equipment_service.GetEquipmentByExtensionRequest.prototype.setExtenstionValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool include_inactive = 3;
 * @return {boolean}
 */
proto.equipment_service.GetEquipmentByExtensionRequest.prototype.getIncludeInactive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.equipment_service.GetEquipmentByExtensionRequest} returns this
 */
proto.equipment_service.GetEquipmentByExtensionRequest.prototype.setIncludeInactive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


goog.object.extend(exports, proto.equipment_service);
