// source: pando/api/vault/v1/events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var pando_api_shared_pb = require('../../../../pando/api/shared_pb.js');
goog.object.extend(proto, pando_api_shared_pb);
goog.exportSymbol('proto.pando.api.vault.v1.events.DocumentAccessed', null, global);
goog.exportSymbol('proto.pando.api.vault.v1.events.Events', null, global);
goog.exportSymbol('proto.pando.api.vault.v1.events.HashChecked', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.vault.v1.events.DocumentAccessed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.pando.api.vault.v1.events.DocumentAccessed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.vault.v1.events.DocumentAccessed.displayName = 'proto.pando.api.vault.v1.events.DocumentAccessed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.vault.v1.events.HashChecked = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pando.api.vault.v1.events.HashChecked, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.vault.v1.events.HashChecked.displayName = 'proto.pando.api.vault.v1.events.HashChecked';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.vault.v1.events.DocumentAccessed.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.vault.v1.events.DocumentAccessed.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.vault.v1.events.DocumentAccessed} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.vault.v1.events.DocumentAccessed.toObject = function(includeInstance, msg) {
  var f, obj = {
    documentGuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userData: (f = msg.getUserData()) && pando_api_shared_pb.UserMetadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.vault.v1.events.DocumentAccessed}
 */
proto.pando.api.vault.v1.events.DocumentAccessed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.vault.v1.events.DocumentAccessed;
  return proto.pando.api.vault.v1.events.DocumentAccessed.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.vault.v1.events.DocumentAccessed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.vault.v1.events.DocumentAccessed}
 */
proto.pando.api.vault.v1.events.DocumentAccessed.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDocumentGuid(value);
      break;
    case 1000:
      var value = new pando_api_shared_pb.UserMetadata;
      reader.readMessage(value,pando_api_shared_pb.UserMetadata.deserializeBinaryFromReader);
      msg.setUserData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.vault.v1.events.DocumentAccessed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.vault.v1.events.DocumentAccessed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.vault.v1.events.DocumentAccessed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.vault.v1.events.DocumentAccessed.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDocumentGuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserData();
  if (f != null) {
    writer.writeMessage(
      1000,
      f,
      pando_api_shared_pb.UserMetadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional string document_guid = 1;
 * @return {string}
 */
proto.pando.api.vault.v1.events.DocumentAccessed.prototype.getDocumentGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.vault.v1.events.DocumentAccessed} returns this
 */
proto.pando.api.vault.v1.events.DocumentAccessed.prototype.setDocumentGuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional pando.api.UserMetadata user_data = 1000;
 * @return {?proto.pando.api.UserMetadata}
 */
proto.pando.api.vault.v1.events.DocumentAccessed.prototype.getUserData = function() {
  return /** @type{?proto.pando.api.UserMetadata} */ (
    jspb.Message.getWrapperField(this, pando_api_shared_pb.UserMetadata, 1000));
};


/**
 * @param {?proto.pando.api.UserMetadata|undefined} value
 * @return {!proto.pando.api.vault.v1.events.DocumentAccessed} returns this
*/
proto.pando.api.vault.v1.events.DocumentAccessed.prototype.setUserData = function(value) {
  return jspb.Message.setWrapperField(this, 1000, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pando.api.vault.v1.events.DocumentAccessed} returns this
 */
proto.pando.api.vault.v1.events.DocumentAccessed.prototype.clearUserData = function() {
  return this.setUserData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pando.api.vault.v1.events.DocumentAccessed.prototype.hasUserData = function() {
  return jspb.Message.getField(this, 1000) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.vault.v1.events.HashChecked.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.vault.v1.events.HashChecked.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.vault.v1.events.HashChecked} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.vault.v1.events.HashChecked.toObject = function(includeInstance, msg) {
  var f, obj = {
    isValid: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    failedId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.vault.v1.events.HashChecked}
 */
proto.pando.api.vault.v1.events.HashChecked.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.vault.v1.events.HashChecked;
  return proto.pando.api.vault.v1.events.HashChecked.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.vault.v1.events.HashChecked} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.vault.v1.events.HashChecked}
 */
proto.pando.api.vault.v1.events.HashChecked.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsValid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFailedId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.vault.v1.events.HashChecked.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.vault.v1.events.HashChecked.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.vault.v1.events.HashChecked} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.vault.v1.events.HashChecked.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsValid();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getFailedId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool is_valid = 1;
 * @return {boolean}
 */
proto.pando.api.vault.v1.events.HashChecked.prototype.getIsValid = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pando.api.vault.v1.events.HashChecked} returns this
 */
proto.pando.api.vault.v1.events.HashChecked.prototype.setIsValid = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string failed_id = 2;
 * @return {string}
 */
proto.pando.api.vault.v1.events.HashChecked.prototype.getFailedId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.vault.v1.events.HashChecked} returns this
 */
proto.pando.api.vault.v1.events.HashChecked.prototype.setFailedId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.pando.api.vault.v1.events.Events = {
  DOCUMENT_RETRIEVED: 0,
  DOCUMENT_UPLOADED: 1,
  CHECK_HASH_CHAIN: 2,
  CHECK_DOCUMENT_HASHES: 3,
  HASH_CHAIN_CHECKED: 4,
  DOCUMENT_HASHES_CHECKED: 5
};

goog.object.extend(exports, proto.pando.api.vault.v1.events);
