// source: pando/api/localization/v1/localization.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var pando_api_localization_v1_services_pb = require('../../../../pando/api/localization/v1/services_pb.js');
goog.object.extend(proto, pando_api_localization_v1_services_pb);
var pando_api_localization_v1_labels_pb = require('../../../../pando/api/localization/v1/labels_pb.js');
goog.object.extend(proto, pando_api_localization_v1_labels_pb);
var pando_api_localization_v1_locales_pb = require('../../../../pando/api/localization/v1/locales_pb.js');
goog.object.extend(proto, pando_api_localization_v1_locales_pb);
goog.exportSymbol('proto.pando.api.localization.v1.CharacterEncoding', null, global);
goog.exportSymbol('proto.pando.api.localization.v1.GetLocalizedTextResponse', null, global);
goog.exportSymbol('proto.pando.api.localization.v1.GetTextsFromLabelsRequest', null, global);
goog.exportSymbol('proto.pando.api.localization.v1.GetTextsFromServicesRequest', null, global);
goog.exportSymbol('proto.pando.api.localization.v1.LocalizedText', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.localization.v1.LocalizedText = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pando.api.localization.v1.LocalizedText, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.localization.v1.LocalizedText.displayName = 'proto.pando.api.localization.v1.LocalizedText';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pando.api.localization.v1.GetTextsFromServicesRequest.repeatedFields_, null);
};
goog.inherits(proto.pando.api.localization.v1.GetTextsFromServicesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.localization.v1.GetTextsFromServicesRequest.displayName = 'proto.pando.api.localization.v1.GetTextsFromServicesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pando.api.localization.v1.GetTextsFromLabelsRequest.repeatedFields_, null);
};
goog.inherits(proto.pando.api.localization.v1.GetTextsFromLabelsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.localization.v1.GetTextsFromLabelsRequest.displayName = 'proto.pando.api.localization.v1.GetTextsFromLabelsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pando.api.localization.v1.GetLocalizedTextResponse.repeatedFields_, null);
};
goog.inherits(proto.pando.api.localization.v1.GetLocalizedTextResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pando.api.localization.v1.GetLocalizedTextResponse.displayName = 'proto.pando.api.localization.v1.GetLocalizedTextResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.localization.v1.LocalizedText.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.localization.v1.LocalizedText.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.localization.v1.LocalizedText} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.localization.v1.LocalizedText.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.localization.v1.LocalizedText}
 */
proto.pando.api.localization.v1.LocalizedText.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.localization.v1.LocalizedText;
  return proto.pando.api.localization.v1.LocalizedText.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.localization.v1.LocalizedText} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.localization.v1.LocalizedText}
 */
proto.pando.api.localization.v1.LocalizedText.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.localization.v1.LocalizedText.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.localization.v1.LocalizedText.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.localization.v1.LocalizedText} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.localization.v1.LocalizedText.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.pando.api.localization.v1.LocalizedText.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pando.api.localization.v1.LocalizedText} returns this
 */
proto.pando.api.localization.v1.LocalizedText.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.localization.v1.GetTextsFromServicesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.localization.v1.GetTextsFromServicesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    servicesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.localization.v1.GetTextsFromServicesRequest}
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.localization.v1.GetTextsFromServicesRequest;
  return proto.pando.api.localization.v1.GetTextsFromServicesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.localization.v1.GetTextsFromServicesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.localization.v1.GetTextsFromServicesRequest}
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<!proto.pando.api.localization.v1.Service>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addServices(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.localization.v1.GetTextsFromServicesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.localization.v1.GetTextsFromServicesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServicesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      1,
      f
    );
  }
};


/**
 * repeated Service services = 1;
 * @return {!Array<!proto.pando.api.localization.v1.Service>}
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.prototype.getServicesList = function() {
  return /** @type {!Array<!proto.pando.api.localization.v1.Service>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<!proto.pando.api.localization.v1.Service>} value
 * @return {!proto.pando.api.localization.v1.GetTextsFromServicesRequest} returns this
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.prototype.setServicesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!proto.pando.api.localization.v1.Service} value
 * @param {number=} opt_index
 * @return {!proto.pando.api.localization.v1.GetTextsFromServicesRequest} returns this
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.prototype.addServices = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pando.api.localization.v1.GetTextsFromServicesRequest} returns this
 */
proto.pando.api.localization.v1.GetTextsFromServicesRequest.prototype.clearServicesList = function() {
  return this.setServicesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.localization.v1.GetTextsFromLabelsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.localization.v1.GetTextsFromLabelsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    labelsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.localization.v1.GetTextsFromLabelsRequest}
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.localization.v1.GetTextsFromLabelsRequest;
  return proto.pando.api.localization.v1.GetTextsFromLabelsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.localization.v1.GetTextsFromLabelsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.localization.v1.GetTextsFromLabelsRequest}
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<!proto.pando.api.localization.v1.Label>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLabels(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.localization.v1.GetTextsFromLabelsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.localization.v1.GetTextsFromLabelsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLabelsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      1,
      f
    );
  }
};


/**
 * repeated Label labels = 1;
 * @return {!Array<!proto.pando.api.localization.v1.Label>}
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.prototype.getLabelsList = function() {
  return /** @type {!Array<!proto.pando.api.localization.v1.Label>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<!proto.pando.api.localization.v1.Label>} value
 * @return {!proto.pando.api.localization.v1.GetTextsFromLabelsRequest} returns this
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.prototype.setLabelsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!proto.pando.api.localization.v1.Label} value
 * @param {number=} opt_index
 * @return {!proto.pando.api.localization.v1.GetTextsFromLabelsRequest} returns this
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.prototype.addLabels = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pando.api.localization.v1.GetTextsFromLabelsRequest} returns this
 */
proto.pando.api.localization.v1.GetTextsFromLabelsRequest.prototype.clearLabelsList = function() {
  return this.setLabelsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pando.api.localization.v1.GetLocalizedTextResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pando.api.localization.v1.GetLocalizedTextResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    encoding: jspb.Message.getFieldWithDefault(msg, 1, 0),
    locale: jspb.Message.getFieldWithDefault(msg, 2, 0),
    localizedTextsList: jspb.Message.toObjectList(msg.getLocalizedTextsList(),
    proto.pando.api.localization.v1.LocalizedText.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pando.api.localization.v1.GetLocalizedTextResponse}
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pando.api.localization.v1.GetLocalizedTextResponse;
  return proto.pando.api.localization.v1.GetLocalizedTextResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pando.api.localization.v1.GetLocalizedTextResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pando.api.localization.v1.GetLocalizedTextResponse}
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.pando.api.localization.v1.CharacterEncoding} */ (reader.readEnum());
      msg.setEncoding(value);
      break;
    case 2:
      var value = /** @type {!proto.pando.api.localization.v1.Locale} */ (reader.readEnum());
      msg.setLocale(value);
      break;
    case 3:
      var value = new proto.pando.api.localization.v1.LocalizedText;
      reader.readMessage(value,proto.pando.api.localization.v1.LocalizedText.deserializeBinaryFromReader);
      msg.addLocalizedTexts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pando.api.localization.v1.GetLocalizedTextResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pando.api.localization.v1.GetLocalizedTextResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEncoding();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getLocale();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getLocalizedTextsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.pando.api.localization.v1.LocalizedText.serializeBinaryToWriter
    );
  }
};


/**
 * optional CharacterEncoding encoding = 1;
 * @return {!proto.pando.api.localization.v1.CharacterEncoding}
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.prototype.getEncoding = function() {
  return /** @type {!proto.pando.api.localization.v1.CharacterEncoding} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.pando.api.localization.v1.CharacterEncoding} value
 * @return {!proto.pando.api.localization.v1.GetLocalizedTextResponse} returns this
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.prototype.setEncoding = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Locale locale = 2;
 * @return {!proto.pando.api.localization.v1.Locale}
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.prototype.getLocale = function() {
  return /** @type {!proto.pando.api.localization.v1.Locale} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.pando.api.localization.v1.Locale} value
 * @return {!proto.pando.api.localization.v1.GetLocalizedTextResponse} returns this
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.prototype.setLocale = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * repeated LocalizedText localized_texts = 3;
 * @return {!Array<!proto.pando.api.localization.v1.LocalizedText>}
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.prototype.getLocalizedTextsList = function() {
  return /** @type{!Array<!proto.pando.api.localization.v1.LocalizedText>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pando.api.localization.v1.LocalizedText, 3));
};


/**
 * @param {!Array<!proto.pando.api.localization.v1.LocalizedText>} value
 * @return {!proto.pando.api.localization.v1.GetLocalizedTextResponse} returns this
*/
proto.pando.api.localization.v1.GetLocalizedTextResponse.prototype.setLocalizedTextsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.pando.api.localization.v1.LocalizedText=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pando.api.localization.v1.LocalizedText}
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.prototype.addLocalizedTexts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.pando.api.localization.v1.LocalizedText, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pando.api.localization.v1.GetLocalizedTextResponse} returns this
 */
proto.pando.api.localization.v1.GetLocalizedTextResponse.prototype.clearLocalizedTextsList = function() {
  return this.setLocalizedTextsList([]);
};


/**
 * @enum {number}
 */
proto.pando.api.localization.v1.CharacterEncoding = {
  UTF_8: 0,
  UTF_16: 1,
  UTF_32: 2
};

goog.object.extend(exports, proto.pando.api.localization.v1);
